name: ci

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Stylua Check
    steps:
      - uses: actions/checkout@v3
      - name: Stylua
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          args: --check .

  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v3
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: dashboard
          version: Nvim 0.8.0
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(doc): auto generate docs'
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

  test:
    name: Run Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: true
          version: nightly

      - name: luajit
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - name: luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: run test
        shell: bash
        run: |
          luarocks install luacheck
          luarocks install vusted
          vusted ./test
